### ISSUE TITLE
tmt tests import fails when run for the second time

### ISSUE THREAD

**Issue by i386x** [teemtee/tmt#1028]
When `tmt tests import` is run for the second time on already imported/converted metada, it is still searching for `Makefile`:
```
~$ tmt tests import
Checking the '/home/jkucera/development/downstream/rhel/passwd-tests/tests/Sanity/smoke-test' directory.
Makefile Unable to open '/home/jkucera/development/downstream/rhel/passwd-tests/tests/Sanity/smoke-test/Makefile'.

~$ tmt tests import --nitrate
Checking the '/home/jkucera/development/downstream/rhel/passwd-tests/tests/Sanity/smoke-test' directory.
Makefile Unable to open '/home/jkucera/development/downstream/rhel/passwd-tests/tests/Sanity/smoke-test/Makefile'.

~$ tmt tests import --nitrate --no-makefile --no-purpose
Checking the '/home/jkucera/development/downstream/rhel/passwd-tests/tests/Sanity/smoke-test' directory.
Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/tmt/cli.py", line 508, in import_
    common, individual = tmt.convert.read(
  File "/usr/lib/python3.10/site-packages/tmt/convert.py", line 388, in read
    beaker_task, data, disabled)
UnboundLocalError: local variable 'beaker_task' referenced before assignment
```

As a test writer, I would like `tmt tests import` prefers existing fmf metadata over Makefiles. Especially, I would like `tmt tests import` to follow the following scenario:
1. load fmf metadata if there are some
2. load metadata from `Makefile` if there is some
   * if `Makefile` metadata conflict with fmf metadata, inform the user and depending on the user choice either exit or prefer `Makefile` metadata (and update fmf metadata accordingly) or prefer fmf metadata
3. load `PURPOSE` if there is some
   * if `PURPOSE` conflicts with fmf metadata, inform the user and depending on the user choice either exit or prefer `PURPOSE` (and update fmf metadata accordingly) or prefer fmf metadata
4. load metadata from Nitrate and update fmf metadata accordingly

*Background*: When a test writer runs `tmt tests import` for the first time, it can take a while to write prepare/finish scripts and plans and to debug the tests before sending them for the review to QE. During the time window between the initial `tmt tests import` and the moment when a test writer is ready to run `tmt tests export`, metadata in TCMS may changed. In this case, `tmt tests import` should be run for the second time to fetch the potential changes from TCMS.

**Comment by psss** [comment]
@i386x, sorry for the late response. Is the issue still causing you problems? I'm not sure it's worth investing time into supporting all these combinations. Would be inclined to close it as there is no plan to invest more resources into `nitrate` integration.

**Comment by i386x** [comment]
Well if there are other ways how to convert metadata, then this issue is irrelevant. In fact, I think that after 3 years all tests should be converted to the new format, so working on this issue will probably be a waste of a time.
