### ISSUE TITLE
tmt clean should not run rsync at all

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#1061]
By mistake I had run `tmt init` in my $HOME. And then I ran `tmt clean`. 
I certainly didn't expect tmt to run rsync of my $HOME to some plan during cleanup.

`ps aux | grep tmt` shows
```
lzachar    20247  5.4  0.0 404152 31712 pts/0    Sl+  11:39   0:03 /usr/bin/python3 -s /usr/bin/tmt clean
lzachar    20248 31.4  0.3 498124 109932 pts/0   D+   11:39   0:16 rsync -ar --exclude .git /home/lzachar/ /var/tmp/tmt/run-044/plans/default/tree
lzachar    20251  4.7  0.0 338896 15508 pts/0    S+   11:39   0:02 rsync -ar --exclude .git /home/lzachar/ /var/tmp/tmt/run-044/plans/default/tree
lzachar    20252 41.5  0.0 410004 16252 pts/0    R+   11:39   0:22 rsync -ar --exclude .git /home/lzachar/ /var/tmp/tmt/run-044/plans/default/tree
```
Dump of active process
```
$ py-spy dump --pid 20247
Process 20247: /usr/bin/python3 -s /usr/bin/tmt clean
Python v3.10.2 (/usr/bin/python3.10)

Thread 20247 (idle): "MainThread"
    _try_wait (subprocess.py:1896)
    _wait (subprocess.py:1938)
    wait (subprocess.py:1204)
    _run (tmt/utils.py:366)
    run (tmt/utils.py:421)
    _initialize_worktree (tmt/base.py:659)
    __init__ (tmt/base.py:563)
    load_from_workdir (tmt/base.py:1453)
    load_run (tmt/utils.py:1237)
    _stop_running_guests (tmt/base.py:1786)
    guests (tmt/base.py:1831)
    clean (tmt/cli.py:999)
    new_func (click/decorators.py:26)
    invoke (click/core.py:762)
    invoke (click/core.py:1404)
    invoke (click/core.py:1646)
    invoke (click/core.py:1668)
    main (click/core.py:1062)
    __call__ (click/core.py:1137)
    <module> (tmt:8)
```

**Comment by idorax** [comment]
Hi @psss and @lukaszachy, I'm looking into this bug.

**Comment by idorax** [comment]
@lukaszachy, would you please let me know what package includes `py-spy` you used?

**Comment by lukaszachy** [comment]
@idorax None, I've used `pip install --user py-spy`

**Comment by lukaszachy** [comment]
It's not that easy :/

Using tmt from your PR: 
```
$ tmt clean guest --dry
clean
    guests
Traceback (most recent call last):
  File "/home/lzachar/.virtualenvs/tmt/bin/tmt", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/lzachar/gits/tmt/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/lzachar/gits/tmt/tmt/cli.py", line 1137, in guests
    if not tmt.Clean(parent=context.obj.clean, context=context).guests():
  File "/home/lzachar/gits/tmt/tmt/base.py", line 1953, in guests
    if not self._stop_running_guests(run):
  File "/home/lzachar/gits/tmt/tmt/base.py", line 1914, in _stop_running_guests
    for plan in run.plans:
  File "/home/lzachar/gits/tmt/tmt/base.py", line 1615, in plans
    self._plans = self.tree.plans(run=self, filters=['enabled:true'])
AttributeError: 'Run' object has no attribute 'tree'. Did you mean: '_tree'?
```

**Comment by idorax** [comment]
@lukaszachy， thanks  for your testing. Looks `tmt.utils.load_run()` is a must.

* https://github.com/teemtee/tmt/blob/main/tmt/utils.py#L1467

```python
def load_run(run: 'tmt.base.Run') -> Tuple[bool, Optional[Exception]]:
    """ Load a run and its steps from the workdir """
    try:
        run.load_from_workdir()
    except GeneralError as error:
        return False, error
    for plan in run.plans:
        for step in plan.steps(disabled=True):
            step.load()
    return True, None
```

If we'd like to skip to run `run.load_from_workdir()`, we have to get the condition that `clean` phase is hit, how can we get it?

**Comment by idorax** [comment]
After looking into the context of `tmt clean`, I failed found a parameter to identify it is because of `tmt clean guests` when the code path is in `class Plan(Core)`.`__init__(self, node, run=None)`. 
* https://github.com/teemtee/tmt/blob/main/tmt/base.py#L595
  ```python
  class Plan(Core):
    """ Plan object (L2 Metadata) """
    ...<snip>...
    def __init__(self, node, run=None):
        """ Initialize the plan """
        super().__init__(node, parent=run)

        # Save the run, prepare worktree and plan data directory
        self.my_run = run
        if self.my_run:
            self._initialize_worktree()
            self._initialize_data_directory()
   ...<snip>...
  ```

So I introduced OPCODE to fix this issue,
1. Introduce OPCODE for CLI subcommands to [tmt/utils.py](https://github.com/teemtee/tmt/blob/main/tmt/utils.py#L94)
2. Set OPCODE in [the entrance of CLI subcommand clean](https://github.com/teemtee/tmt/blob/main/tmt/cli.py#L1058), e.g. 
    ```python
    context.params['opcode'] = tmt.utils.OPCODE_CLI_SUBCMD_CLEAN
    ```
3. Check the OPCODE in `class Plan(Core)`.`__init__(self, node, run=None)` in [tmt/base.py](https://github.com/teemtee/tmt/blob/main/tmt/base.py#L595). If the OPCODE is `OPCODE_CLI_SUBCMD_CLEAN`, skip to call `Plan()._initialize_worktree()`

Hi @lukaszachy, @FrNecas and @psss, please help to review, thanks very much!
