### ISSUE TITLE
tmt import does not authenticate

### ISSUE THREAD

**Issue by hhorak** [teemtee/tmt#1087]
Trying to re-import data (make `tmt` to recreate `main.fmf`) that is related to the PR https://src.osci.redhat.com/tests/mariadb55/pull-request/9. I get:
```
$ tmt -r ../.. test import 
Checking the '/home/hhorak/rhel/mariadb/mariadb-tests/Sanity/daemon-selinux-context' directory.
Makefile found in '/home/hhorak/rhel/mariadb/mariadb-tests/Sanity/daemon-selinux-context/Makefile'.
task: /CoreOS/mariadb/Sanity/daemon-selinux-context
summary: Checks if daemon is running in correct selinux context
test: ./runtest.sh
framework: beakerlib
contact: Branislav Blaskovic <bblaskov@redhat.com>
component: mariadb
duration: 5m
require: library(mariadb55/basic)
recommend: mariadb mariadb-server
Purpose found in '/home/hhorak/rhel/mariadb/mariadb-tests/Sanity/daemon-selinux-context/PURPOSE'.
description:

Nitrate Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/nitrate/base.py", line 200, in _server
    Config().nitrate.username,
AttributeError: 'Section' object has no attribute 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/nitrate/xmlrpc_driver.py", line 393, in do_command
    return getattr(self.server, verb)(*params)
  File "/usr/lib64/python3.10/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.10/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/lib64/python3.10/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.10/site-packages/nitrate/xmlrpc_driver.py", line 129, in single_request_with_cookies
    raise xmlrpclib.ProtocolError(
xmlrpc.client.ProtocolError: <ProtocolError for tcms.engineering.redhat.com/xmlrpc/: 401 Authorization Required>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/tmt/cli.py", line 508, in import_
    common, individual = tmt.convert.read(
  File "/usr/lib/python3.10/site-packages/tmt/convert.py", line 388, in read
    common_data, individual_data = read_nitrate(
  File "/usr/lib/python3.10/site-packages/tmt/convert.py", line 431, in read_nitrate
    testcases = list(nitrate.TestCase.search(
  File "/usr/lib/python3.10/site-packages/nitrate/mutable.py", line 912, in search
    for inject in Nitrate()._server.TestCase.filter(dict(query))]
  File "/usr/lib/python3.10/site-packages/nitrate/base.py", line 205, in _server
    Nitrate._connection = xmlrpc_driver.NitrateKerbXmlrpc(
  File "/usr/lib/python3.10/site-packages/nitrate/xmlrpc_driver.py", line 443, in __init__
    login_dict = self.do_command("Auth.login_krbv", [])
  File "/usr/lib/python3.10/site-packages/nitrate/xmlrpc_driver.py", line 395, in do_command
    raise NitrateXmlrpcError(verb, str(params), e)
nitrate.xmlrpc_driver.NitrateXmlrpcError: Error while executing cmd 'Auth.login_krbv([])' --> <ProtocolError for tcms.engineering.redhat.com/xmlrpc/: 401 Authorization Required>
[hhorak@hhorak-t490s daemon-selinux-context] (fmf-daemon-selinux-context %)$ klist 
Ticket cache: KCM:16119:93577
Default principal: hhorak@REDHAT.COM

Valid starting       Expires              Service principal
03/07/2022 17:20:02  03/08/2022 03:20:02  krbtgt/REDHAT.COM@REDHAT.COM
03/07/2022 17:20:04  03/08/2022 03:20:02  HTTP/tcms.engineering.redhat.com@
	Ticket server: HTTP/tcms.engineering.redhat.com@REDHAT.COM

```
Using this version:
```
tmt-redhat-provision-minute-0.8-3.noarch
python3-tmt-1.11.0-1.20220304224842340357.main.2.gd0d7461.fc35.noarch
tmt-1.11.0-1.20220304224842340357.main.2.gd0d7461.fc35.noarch
tmt-provision-container-1.11.0-1.20220304224842340357.main.2.gd0d7461.fc35.noarch
```

**Comment by thrix** [comment]
FTR https://issues.redhat.com/browse/EXDSP-587

**Comment by hhorak** [comment]
yay, it made the trick, thanks!
