### ISSUE TITLE
Traceback when connect is used without cli arguments

### ISSUE THREAD

**Issue by RHEmployee** [teemtee/tmt#1093]
`tmt -vvvddd run provision -h connect`

Exception is throw inside exception.

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/tmt/steps/provision/__init__.py", line 124, in go
    plugin.go()
  File "/usr/lib/python3.9/site-packages/tmt/steps/provision/connect.py", line 91, in go
    raise tmt.utils.SpecificationError(
tmt.utils.SpecificationError: Provide a host name or an ip address to connect.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1290, in invoke
    return _process_result(rv)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1224, in _process_result
    value = ctx.invoke(self.result_callback, value, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tmt/cli.py", line 337, in finito
    click_context.obj.run.go()
  File "/usr/lib/python3.9/site-packages/tmt/base.py", line 1620, in go
    plan.go()
  File "/usr/lib/python3.9/site-packages/tmt/base.py", line 925, in go
    step.go()
  File "/usr/lib/python3.9/site-packages/tmt/steps/provision/__init__.py", line 145, in go
    self.save()
  File "/usr/lib/python3.9/site-packages/tmt/steps/provision/__init__.py", line 63, in save
    [(guest.name, guest.save()) for guest in self.guests()])
  File "/usr/lib/python3.9/site-packages/tmt/steps/provision/__init__.py", line 63, in <listcomp>
    [(guest.name, guest.save()) for guest in self.guests()])
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by RHEmployee** [comment]
I can take a look at this :).

**Comment by RHEmployee** [comment]
Hi. Merged so this can be closed.

**Comment by psss** [comment]
It was closed about a month ago.

**Comment by RHEmployee** [comment]
Ah.. My fault. Thanks. Strange that I was able to click on: "close and comment". Maybe cache in browser? Not sure :).
