### ISSUE TITLE
tmt should fail nicely if HEAD not around

### ISSUE THREAD

**Issue by thrix** [teemtee/tmt#1115]
`tmt` now fails fairly cryptically on this corner case, it should print a nice error instead

```
# STDOUT:
---v---v---v---v---v---
/var/ARTIFACTS/work-cii6cubV
Found 1 plan.

/plans/ci
summary: CI test plan that runs only modified tests
    discover
        how: fmf
        directory: /var/ARTIFACTS/workdir-repository-None-ooCYjI
        hash: 661de82
        modified-url: https://src.osci.redhat.com/tests/netlabel_tools.git
    finish
        summary: 0 tasks completed

---^---^---^---^---^---

# STDERR:
---v---v---v---v---v---
error: Cannot determine remote HEAD
Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 721, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1065, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1092, in invoke
    return _process_result(rv)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1030, in _process_result
    **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/tmt/cli.py", line 337, in finito
    click_context.obj.run.go()
  File "/usr/lib/python3.6/site-packages/tmt/base.py", line 1586, in go
    plan.go()
  File "/usr/lib/python3.6/site-packages/tmt/base.py", line 891, in go
    step.go()
  File "/usr/lib/python3.6/site-packages/tmt/steps/discover/__init__.py", line 131, in go
    plugin.go()
  File "/usr/lib/python3.6/site-packages/tmt/steps/discover/fmf.py", line 248, in go
    'modified-ref', tmt.utils.default_branch(testdir))
  File "/usr/lib/python3.6/site-packages/tmt/utils.py", line 1154, in default_branch
    with open(head) as ref:
FileNotFoundError: [Errno 2] No such file or directory: '/var/ARTIFACTS/work-cii6cubV/plans/ci/discover/default/tests/.git/refs/remotes/origin/HEAD'
```

**Comment by psss** [comment]
Seems to be fixed now.
