### ISSUE TITLE
test import fails when importing Makefile without “build:” element

### ISSUE THREAD

**Issue by sbertramrh** [teemtee/tmt#1131]
Error message:
[sbertram@sbertram header-test]$ tmt tests import
Checking the '/home/sbertram/gitstuff/kernel-tmt/misc/header-test' directory.
Makefile found in '/home/sbertram/gitstuff/kernel-tmt/misc/header-test/Makefile'.
task: /kernel/misc/header-test
summary: Sanity test for kernel-headers
test: ./runtest.sh
framework: shell
contact: 
component: kernel
duration: 10m
recommend: kernel-headers gcc bash python python2 python3 gcc
Traceback (most recent call last):
  File "/home/sbertram/.local/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/home/sbertram/.local/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/sbertram/.local/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/sbertram/.local/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sbertram/.local/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sbertram/.local/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sbertram/.local/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sbertram/.local/lib/python3.6/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sbertram/.local/lib/python3.6/site-packages/tmt/cli.py", line 522, in import_
    path, makefile, restraint, nitrate, purpose, disabled, types)
  **File "/home/sbertram/.local/lib/python3.6/site-packages/tmt/convert.py", line 445, in read
    build_target_list = target_content("build")**
  File "/home/sbertram/.local/lib/python3.6/site-packages/tmt/convert.py", line 433, in target_content
    target = re.search(regexp, datafile, re.M).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

After adding: 
build:
     chmod +x ./runtest.sh

to the Makefile it was able to successfully process and convert.

[sbertram@sbertram header-test]$ tmt tests import
Checking the '/home/sbertram/gitstuff/kernel-tmt/misc/header-test' directory.
Makefile found in '/home/sbertram/gitstuff/kernel-tmt/misc/header-test/Makefile'.
task: /kernel/misc/header-test
summary: Sanity test for kernel-headers
test: ./runtest.sh
framework: shell
contact:
component: kernel
duration: 10m
recommend: kernel-headers gcc bash python python2 python3 gcc
Purpose found in '/home/sbertram/gitstuff/kernel-tmt/misc/header-test/PURPOSE'.
description:
This test will try to compile each kernel header file with gcc.
.
.
.
Metadata successfully stored into '/home/sbertram/gitstuff/kernel-tmt/misc/header-test/main.fmf'.

To reproduce try and convert a Makefile missing the build: element.

**Comment by lukaszachy** [comment]
Should be fixed by #1150
