### ISSUE TITLE
tmt test import tracebacks

### ISSUE THREAD

**Issue by milosmalik** [teemtee/tmt#1147]
```
$ cd /tmp/
$ git clone https://src.fedoraproject.org/tests/selinux
Cloning into 'selinux'...
remote: Enumerating objects: 821, done.
remote: Counting objects: 100% (821/821), done.
remote: Compressing objects: 100% (238/238), done.
remote: Total 2820 (delta 707), reused 600 (delta 583), pack-reused 1999
Receiving objects: 100% (2820/2820), 633.92 KiB | 198.00 KiB/s, done.
Resolving deltas: 100% (1647/1647), done.
$ cd selinux/policycoreutils/restorecond_pointer_abuse/
$ tmt test import --nitrate --purpose --makefile -v
Checking the '/tmp/selinux/policycoreutils/restorecond_pointer_abuse' directory.
Makefile found in '/tmp/selinux/policycoreutils/restorecond_pointer_abuse/Makefile'.
task: /CoreOS/policycoreutils/Regression/restorecond_pointer_abuse
summary: Is restorecond flooding logs with blob data messages?
test: ./runtest.sh
framework: beakerlib
contact: Vit Mojzis <vmojzis@redhat.com>
component: policycoreutils
duration: 10m
recommend: git /usr/sbin/restorecond /usr/bin/chcon /usr/sbin/sestatus /usr/bin/systemctl /usr/bin/journalctl
relates: https://bugzilla.redhat.com/show_bug.cgi?id=1626468
Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tmt/cli.py", line 508, in import_
    common, individual = tmt.convert.read(
  File "/usr/lib/python3.9/site-packages/tmt/convert.py", line 349, in read
    build_target_list = target_content("build")
  File "/usr/lib/python3.9/site-packages/tmt/convert.py", line 337, in target_content
    target = re.search(regexp, makefile, re.M).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
$
```
Following TMT packages are installed on my machine:
tmt-1.9.0-1.20211206173159577165.master.3.g745dcb9.fc33.noarch
tmt-test-convert-1.9.0-1.20211206173159577165.master.3.g745dcb9.fc33.noarch

**Comment by lukaszachy** [comment]
Makefile is missing `build` section. AFAIK it is not compulsory to have it there so tmt should cope with that.
