### ISSUE TITLE
traceback when kerberos is configured badly: tmt test convert .

### ISSUE THREAD

**Issue by RHEmployee** [teemtee/tmt#1181]
`$ tmt test convert  .`

```
Nitrate Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/nitrate/base.py", line 200, in _server
    Config().nitrate.username,
AttributeError: 'Section' object has no attribute 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/nitrate/xmlrpc_driver.py", line 393, in do_command
    return getattr(self.server, verb)(*params)
  File "/usr/lib64/python3.10/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.10/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/lib64/python3.10/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.10/site-packages/nitrate/xmlrpc_driver.py", line 129, in single_request_with_cookies
    raise xmlrpclib.ProtocolError(
xmlrpc.client.ProtocolError: <ProtocolError for tcms.engineering.redhat.com/xmlrpc/: 401 Authorization Required>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/tmt/cli.py", line 521, in import_
    common, individual = tmt.convert.read(
  File "/usr/lib/python3.10/site-packages/tmt/convert.py", line 487, in read
    common_data, individual_data = read_nitrate(
  File "/usr/lib/python3.10/site-packages/tmt/convert.py", line 530, in read_nitrate
    testcases = list(nitrate.TestCase.search(
  File "/usr/lib/python3.10/site-packages/nitrate/mutable.py", line 912, in search
    for inject in Nitrate()._server.TestCase.filter(dict(query))]
  File "/usr/lib/python3.10/site-packages/nitrate/base.py", line 205, in _server
    Nitrate._connection = xmlrpc_driver.NitrateKerbXmlrpc(
  File "/usr/lib/python3.10/site-packages/nitrate/xmlrpc_driver.py", line 443, in __init__
    login_dict = self.do_command("Auth.login_krbv", [])
  File "/usr/lib/python3.10/site-packages/nitrate/xmlrpc_driver.py", line 395, in do_command
    raise NitrateXmlrpcError(verb, str(params), e)
nitrate.xmlrpc_driver.NitrateXmlrpcError: Error while executing cmd 'Auth.login_krbv([])' --> <ProtocolError for tcms.engineering.redhat.com/xmlrpc/: 401 Authorization Required>
```

maybe tmt should handle this exception

**Comment by psss** [comment]
> AttributeError: 'Section' object has no attribute 'username'

I'd say `nitrate` should catch this first and raise a `NitrateError` exception? @lukaszachy, @ZelenyMartin, thoughts?

**Comment by lukaszachy** [comment]
Well, yes. But from UX tmt will need to require newer python-nitrate (one which has this bug fixed)

**Comment by RHEmployee** [comment]
Note: this can happen because move to different kind of krb.
After using new configs provided, there is no issue of this kind. 
But from user standpoint it should be more friendly.

Maybe I can test this without ticket also.

**Comment by lukaszachy** [comment]
It's connected to https://bugzilla.redhat.com/show_bug.cgi?id=1481213
However tmt is using nitrate so it should take care of its exceptions
