### ISSUE TITLE
Traceback when defining context in a test plan

### ISSUE THREAD

**Issue by kkaarreell** [teemtee/tmt#1187]
I wanted to introduce custom context in a plan and use it for test filtering.
When having `main.fmf` like this:
```
context:
  swtpm: 1
```
`tmt` discover ends with a Traceback.
```
$ tmt run discover -h fmf -vvv plan -n upstream
/var/tmp/tmt/run-118

/plans/upstream-keylime-tests-github-ci
    discover
        how: fmf
        order: 50
        directory: /home/ksrot/devel/github/keylime-tests
        hash: c91c0cb
        tests: /setup/configure_tpm_emulator, /setup/install_upstream_keylime, /setup/enable_keylime_coverage, /functional/.*, /upstream/run_keylime_tests and /setup/generate_coverage_report
Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 721, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1065, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1092, in invoke
    return _process_result(rv)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1030, in _process_result
    **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/tmt/cli.py", line 345, in finito
    click_context.obj.run.go()
  File "/usr/lib/python3.6/site-packages/tmt/base.py", line 1722, in go
    plan.go()
  File "/usr/lib/python3.6/site-packages/tmt/base.py", line 958, in go
    step.go()
  File "/usr/lib/python3.6/site-packages/tmt/steps/discover/__init__.py", line 139, in go
    plugin.go()
  File "/usr/lib/python3.6/site-packages/tmt/steps/discover/fmf.py", line 323, in go
    excludes=excludes)
  File "/usr/lib/python3.6/site-packages/tmt/base.py", line 1324, in tests
    in name_filter(self.tree.prune(keys=keys, names=[name]))]
  File "/usr/lib/python3.6/site-packages/tmt/base.py", line 1283, in tree
    self._tree.adjust(fmf.context.Context(**self._fmf_context()))
  File "/usr/lib/python3.6/site-packages/fmf/context.py", line 391, in __init__
    [self.parse_value(val) for val in values]
  File "/usr/lib/python3.6/site-packages/fmf/context.py", line 391, in <listcomp>
    [self.parse_value(val) for val in values]
  File "/usr/lib/python3.6/site-packages/fmf/context.py", line 435, in parse_value
    return ContextValue(value)
  File "/usr/lib/python3.6/site-packages/fmf/context.py", line 45, in __init__
    self._to_compare = self._split_to_version(origin)
  File "/usr/lib/python3.6/site-packages/fmf/context.py", line 178, in _split_to_version
    return tuple(re.split(r":|-|\.", text))
  File "/usr/lib64/python3.6/re.py", line 212, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: expected string or bytes-like object
```
The problem is in `return tuple(re.split(r":|-|\.", text))` because what is called here a "text" is in fact an object returned by YAML parser. In my case it is a number `1` but the same applies also to `true`.

Fixed/workaround that worked for me was to replace explicitly convert to string but I guess there could be even better way how to approach it.
```
return tuple(re.split(r":|-|\.", str(text)))
```
Btw, defining the same context from `tmt` command line works fine (most probably because cmdline arguments are parsed as strings).

**Comment by thrix** [comment]
@kkaarreell thanks for the report, I will look at it

**Comment by kkaarreell** [comment]
Thinking about it, I would probably do the conversion sooner, e.g.
```
return ContextValue(str(value) )
```
or even sooner in
```
[self.parse_value(str(val)) for val in values]
```

**Comment by thrix** [comment]
I believe ContextValue is the correct place, proposed under: 
https://github.com/teemtee/fmf/pull/167
