### ISSUE TITLE
Regression in login -s execute for released v1.13.0

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#1211]
Reproducer (on 1.13.0, current main is fixed), this should have been cough by test suite but wasn't
```
$ tmt init -t base
$ tmt run login -s execute

Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1691, in invoke
    return _process_result(rv)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1628, in _process_result
    value = ctx.invoke(self._result_callback, value, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/tmt/cli.py", line 345, in finito
    click_context.obj.run.go()
  File "/usr/lib/python3.10/site-packages/tmt/base.py", line 1694, in go
    plan.go()
  File "/usr/lib/python3.10/site-packages/tmt/base.py", line 943, in go
    step.go()
  File "/usr/lib/python3.10/site-packages/tmt/steps/execute/__init__.py", line 141, in go
    if plugin.enabled_on_guest(guest):
AttributeError: 'Login' object has no attribute 'enabled_on_guest'
```

**Comment by lukaszachy** [comment]
09c57ceaac36bb7de0904918cc209746258ce429 added a test
