### ISSUE TITLE
Apache library test fails when run under `/tests/full`

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#1232]
The apache plan from the `/tests/discover/libraries` fails when executed under `/test/full`:

```
total: 1 test passed
Clean up workdir '/var/tmp/tmt/run-001'.
Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1691, in invoke
    return _process_result(rv)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1628, in _process_result
    value = ctx.invoke(self._result_callback, value, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/tmt/cli.py", line 346, in finito
    click_context.obj.run.go()
  File "/usr/lib/python3.10/site-packages/tmt/base.py", line 1768, in go
    self.finish()
  File "/usr/lib/python3.10/site-packages/tmt/base.py", line 1652, in finish
    self._workdir_cleanup(self.workdir)
  File "/usr/lib/python3.10/site-packages/tmt/utils.py", line 710, in _workdir_cleanup
    shutil.rmtree(directory)
  File "/usr/lib64/python3.10/shutil.py", line 722, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib64/python3.10/shutil.py", line 655, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib64/python3.10/shutil.py", line 655, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib64/python3.10/shutil.py", line 655, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  [Previous line repeated 9 more times]
  File "/usr/lib64/python3.10/shutil.py", line 678, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib64/python3.10/shutil.py", line 676, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: '002c0b4f.0'
```

The problem appears during workdir cleanup, the plan itself passes. Works fine when run outside the `/test/full` suite.

```
cd tests/discover/libraries/data/
tmt run -vvvddd plan -n apache
...
total: 1 test passed
```

@lukaszachy, could you possibly have a look?

**Comment by lukaszachy** [comment]
Should be fixed with #1239 (if accepted that way)
