### ISSUE TITLE
convert fail if mail does not exist

### ISSUE THREAD

**Issue by psklenar** [teemtee/tmt#1233]
summary: /CoreOS/dhcp/Regression/bz1668696-OVN-dhclient-doesn-t-update-resolv-conf-in
script: /CoreOS/dhcp/Regression/bz1668696-OVN-dhclient-doesn-t-update-resolv-conf-in
components: dhcp
tags: fmf-export
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/nitrate/immutable.py", line 866, in _fetch
    inject = self._server.User.filter({"email": self.email})[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/tmt/cli.py", line 583, in export
    test.export(format_='nitrate')
  File "/usr/lib/python3.10/site-packages/tmt/base.py", line 547, in export
    tmt.export.export_to_nitrate(self)
  File "/usr/lib/python3.10/site-packages/tmt/export.py", line 338, in export_to_nitrate
    nitrate_case.tester = nitrate.User(email_address)
  File "/usr/lib/python3.10/site-packages/nitrate/base.py", line 87, in setter
    log.info(u"Updating {0}'s {1} to '{2}'".format(
  File "/usr/lib/python3.10/site-packages/nitrate/base.py", line 356, in __str__
    return self.__unicode__()
  File "/usr/lib/python3.10/site-packages/nitrate/immutable.py", line 832, in __unicode__
    return self.name if self.name is not None else u"No Name"
  File "/usr/lib/python3.10/site-packages/nitrate/base.py", line 65, in getter
    self._fetch()
  File "/usr/lib/python3.10/site-packages/nitrate/immutable.py", line 868, in _fetch
    raise NitrateError("No user found for email '{0}'".format(
nitrate.xmlrpc_driver.NitrateError: No user found for email 'pavel@redhat.com'
[master a32346f] tmt 1

there is pavel@redhat.com in:
http://pkgs.devel.redhat.com/cgit/tests/dhcp/tree/Regression/bz1668696-OVN-dhclient-doesn-t-update-resolv-conf-in/main.fmf

**Comment by psklenar** [comment]
fyi I uncommented the mail address, to be able to continue with converts

**Comment by lukaszachy** [comment]
`tmt tests export --nitrate` should fail with reasonable error stating that user doesn't exist.
We should document that first item of contact is taken as default tester (I'm not able to find it stated in docs)
