### ISSUE TITLE
Uncaught exception when downloading image (testcloud)

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#1265]
Probably network hickup however tmt shouldn't print traceback
```
                out:         Guessed image url: 'https://download.fedoraproject.org/pub/fedora/linux/releases/35/Cloud/x86_64/images/Fedora-Cloud-Base-35-1.2.x86_64.qcow2'
                out:         qcow: Fedora-Cloud-Base-35-1.2.x86_64.qcow2
                out:         progress: downloading...
                out:     Write file '/var/tmp/tmt/run-upgrade/plan/path/provision/step.yaml'.
                out:     Write file '/var/tmp/tmt/run-upgrade/plan/path/provision/guests.yaml'.
                out: Traceback (most recent call last):
                out:   File "/usr/bin/tmt", line 8, in <module>
                out:     tmt.cli.main()
                out:   File "/usr/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
                out:     return self.main(*args, **kwargs)
                out:   File "/usr/lib/python3.10/site-packages/click/core.py", line 1053, in main
                out:     rv = self.invoke(ctx)
                out:   File "/usr/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
                out:     return _process_result(sub_ctx.command.invoke(sub_ctx))
                out:   File "/usr/lib/python3.10/site-packages/click/core.py", line 1691, in invoke
                out:     return _process_result(rv)
                out:   File "/usr/lib/python3.10/site-packages/click/core.py", line 1628, in _process_result
                out:     value = ctx.invoke(self._result_callback, value, **ctx.params)
                out:   File "/usr/lib/python3.10/site-packages/click/core.py", line 754, in invoke
                out:     return __callback(*args, **kwargs)
                out:   File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
                out:     return f(get_current_context(), *args, **kwargs)
                out:   File "/usr/lib/python3.10/site-packages/tmt/cli.py", line 346, in finito
                out:     click_context.obj.run.go()
                out:   File "/usr/lib/python3.10/site-packages/tmt/base.py", line 1761, in go
                out:     plan.go()
                out:   File "/usr/lib/python3.10/site-packages/tmt/base.py", line 997, in go
                out:     step.go()
                out:   File "/usr/lib/python3.10/site-packages/tmt/steps/provision/__init__.py", line 132, in go
                out:     phase.go()
                out:   File "/usr/lib/python3.10/site-packages/tmt/steps/provision/testcloud.py", line 265, in go
                out:     self._guest.start()
                out:   File "/usr/lib/python3.10/site-packages/tmt/steps/provision/testcloud.py", line 481, in start
                out:     self._image.prepare()
                out:   File "/usr/lib/python3.10/site-packages/testcloud/image.py", line 271, in prepare
                out:     self._download_remote_image(self.remote_path, self.local_path)
                out:   File "/usr/lib/python3.10/site-packages/testcloud/image.py", line 136, in _download_remote_image
                out:     file_size = int(u.headers['content-length'])
                out:   File "/usr/lib/python3.10/site-packages/requests/structures.py", line 54, in __getitem__
                out:     return self._store[key.lower()][1]
                out: KeyError: 'content-length'
```

**Comment by lukaszachy** [comment]
Not sure if worth separate issue so: finish ran after exception above ends with its own traceback
```
                out: :: [ 09:43:18 ] :: [  BEGIN   ] :: Stop the guest and remove the workdir :: actually running 'tmt run -l finish'
                out: /var/tmp/tmt/run-upgrade
                out: 
                out: /plan/path
                out: Traceback (most recent call last):
                out:   File "/usr/bin/tmt", line 8, in <module>
                out:     tmt.cli.main()
                out:   File "/usr/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
                out:     return self.main(*args, **kwargs)
                out:   File "/usr/lib/python3.10/site-packages/click/core.py", line 1053, in main
                out:     rv = self.invoke(ctx)
                out:   File "/usr/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
                out:     return _process_result(sub_ctx.command.invoke(sub_ctx))
                out:   File "/usr/lib/python3.10/site-packages/click/core.py", line 1691, in invoke
                out:     return _process_result(rv)
                out:   File "/usr/lib/python3.10/site-packages/click/core.py", line 1628, in _process_result
                out:     value = ctx.invoke(self._result_callback, value, **ctx.params)
                out:   File "/usr/lib/python3.10/site-packages/click/core.py", line 754, in invoke
                out:     return __callback(*args, **kwargs)
                out:   File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
                out:     return f(get_current_context(), *args, **kwargs)
                out:   File "/usr/lib/python3.10/site-packages/tmt/cli.py", line 346, in finito
                out:     click_context.obj.run.go()
                out:   File "/usr/lib/python3.10/site-packages/tmt/base.py", line 1761, in go
                out:     plan.go()
                out:   File "/usr/lib/python3.10/site-packages/tmt/base.py", line 957, in go
                out:     step.wake()
                out:   File "/usr/lib/python3.10/site-packages/tmt/steps/provision/__init__.py", line 85, in wake
                out:     plugin.wake(data=self._guest_data.get(plugin.name))
                out:   File "/usr/lib/python3.10/site-packages/tmt/steps/provision/testcloud.py", line 242, in wake
                out:     guest.wake()
                out:   File "/usr/lib/python3.10/site-packages/tmt/steps/provision/testcloud.py", line 416, in wake
                out:     self._instance = testcloud.instance.Instance(
                out:   File "/usr/lib/python3.10/site-packages/testcloud/instance.py", line 242, in __init__
                out:     self.image_path = os.path.join(config_data.DATA_DIR, "instances", self.name, self.name + "-local.qcow2")
                out: TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```
