### ISSUE TITLE
Cleanup and status fails for older runs

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#1422]
When there is an older run generated using `tmt < 1.16` the `tmt status` and `tmt clean` commands fail with a traceback:

```
Traceback (most recent call last):
  File "/home/psss/.virtualenvs/tmt/bin/tmt", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/psss/git/tmt/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/home/psss/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/psss/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/psss/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/psss/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 1690, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/psss/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/psss/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/psss/.virtualenvs/tmt/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/psss/git/tmt/tmt/cli.py", line 1349, in clean_guests
    if not tmt.Clean(parent=context.obj.clean, context=context).guests():
  File "/home/psss/git/tmt/tmt/base.py", line 2082, in guests
    if not self._stop_running_guests(run):
  File "/home/psss/git/tmt/tmt/base.py", line 2037, in _stop_running_guests
    loaded, error = tmt.utils.load_run(run)
  File "/home/psss/git/tmt/tmt/utils.py", line 1940, in load_run
    step.load()
  File "/home/psss/git/tmt/tmt/steps/provision/__init__.py", line 67, in load
    self._guest_data = {
  File "/home/psss/git/tmt/tmt/steps/provision/__init__.py", line 68, in <dictcomp>
    name: tmt.utils.SerializableContainer.unserialize(guest_data)
  File "/home/psss/git/tmt/tmt/utils.py", line 1381, in unserialize
    klass_info = serialized.pop('__class__')
KeyError: '__class__'
```

This is caused by missing class information stored by newer implementation of guest data. @happz, do you see any quick solution for that or shall we just live with that and recommend doing a manual `rm -rf /var/tmp/tmt/run*` cleanup of old runs?

**Comment by thrix** [comment]
I would even say the failure should be caught and printed more reasonably for the user, that the internal metadata change and `tmt clean runs` should be run?

**Comment by happz** [comment]
I'd add a better error message - this may happen, and there's no easy way around it, because without `__class__` key, serialization cannot pick correct class to construct.

@psss would that be good enough?

**Comment by FrNecas** [comment]
+1 to error message. I think `tmt clean runs` should work even with the old metadata, though it has to be verified. We do not load the runs in `tmt clean runs` unless `--last` is used, the directories are just removed.

**Comment by psss** [comment]
Yeah, a reasonable error message make sense. Should be covered by #1423.
