### ISSUE TITLE
Traceback due to a space before tag in filter

### ISSUE THREAD

**Issue by kkaarreell** [teemtee/tmt#1459]
Due to having
```
filter: tag: CI-Tier-1 | tag: CI-Tier-1-IMA
```
I got
```
$ tmt run discover -vvv plan -f 'tier: 1'
/var/tmp/tmt/run-098

/plans/tier1-swtpm
    discover
        how: fmf
        name: Setup
        order: 50
        url: https://github.com/RedHat-SP-Security/keylime-tests
        ref: main
        hash: b2916be
        tests: /setup/configure-repo-with-rpms-from-brew, /setup/configure_tpm_emulator and /setup/configure_kernel_ima_module/ima_policy_signing
        how: fmf
        name: Tests
        order: 50
        url: https://github.com/RedHat-SP-Security/keylime-tests
        ref: main
        hash: b2916be
        filter: {'tag': 'CI-Tier-1'}
        filter: {'tag': 'CI-Tier-1-IMA'}
Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 721, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1065, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1092, in invoke
    return _process_result(rv)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1030, in _process_result
    **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/tmt/cli.py", line 384, in finito
    click_context.obj.run.go()
  File "/usr/lib/python3.6/site-packages/tmt/base.py", line 1822, in go
    plan.go()
  File "/usr/lib/python3.6/site-packages/tmt/base.py", line 1040, in go
    step.go()
  File "/usr/lib/python3.6/site-packages/tmt/steps/discover/__init__.py", line 154, in go
    phase.go()
  File "/usr/lib/python3.6/site-packages/tmt/steps/discover/fmf.py", line 455, in go
    excludes=excludes)
  File "/usr/lib/python3.6/site-packages/tmt/base.py", line 1422, in tests
    tests, filters, conditions, links, excludes)
  File "/usr/lib/python3.6/site-packages/tmt/base.py", line 1333, in _filters_conditions
    for filter_ in filters]):
  File "/usr/lib/python3.6/site-packages/tmt/base.py", line 1333, in <listcomp>
    for filter_ in filters]):
  File "/usr/lib/python3.6/site-packages/fmf/utils.py", line 324, in filter
    for clause in re.split(r"\s*\|\s*", filter)])
  File "/usr/lib64/python3.6/re.py", line 212, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: expected string or bytes-like object
```
There should be no space between `tag:` and `CI-Tier-1` which is a bit unfortunate.

**Comment by lukaszachy** [comment]
Just a first look but isn't that due `for clause in re.split(r"\s*\|\s*", filter)])` is calling 'filter' and not 'filter_' ?

**Comment by kkaarreell** [comment]
I am sorry, this is my bad, it seems I saw/copied different traceback which appeared when providing filter as a list item. I think you can close this issue. Sorry for the noise.

**Comment by lukaszachy** [comment]
No problem. Just for future visitors: in plan.fmf one has to do `filter: "tag: CI-Tier-1 | tag: CI-Tier-1-IMA"` otherwise it is a yaml syntax error.
