### ISSUE TITLE
tmt test export --how nitrate . to fedora repo with master branch tracebacks

### ISSUE THREAD

**Issue by Athwale** [teemtee/tmt#1785]
Doing export from a fedora tests repo where the branch is master.
```
user@fedora wget (master)$ git branch
* master
```
Gives a traceback:
```
tmt test export --how nitrate 
Test case 'TC#0010047' found.
error: Not a valid ref: refs/remotes/origin/main
Traceback (most recent call last):
  File "/usr/bin/tmt", line 20, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/tmt/cli.py", line 637, in tests_export
    test.export(format_=tmt.base.ExportFormat(how))  # type: ignore[call-overload]
  File "/usr/lib/python3.10/site-packages/tmt/base.py", line 942, in export
    return tmt.export.export_to_nitrate(self)
  File "/usr/lib/python3.10/site-packages/tmt/export.py", line 485, in export_to_nitrate
    check_git_url(test.fmf_id.url)
  File "/usr/lib/python3.10/site-packages/tmt/base.py", line 468, in fmf_id
    return tmt.utils.fmf_id(self.name, self.node.root)
  File "/usr/lib/python3.10/site-packages/tmt/utils.py", line 2128, in fmf_id
    def_branch = default_branch(git_root)
  File "/usr/lib/python3.10/site-packages/tmt/utils.py", line 2268, in default_branch
    with open(head) as ref:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/tests_fedora/wget/.git/refs/remotes/origin/HEAD'
```

Cloning the same repo again with the same command the second time cloned the main branch and that fixed the problem.
So I can not reproduce it now. I guess this is some issue with master to main redirection.

**Comment by psss** [comment]
No significant time investments planned for nitrate integration in the near future. Closing. Feel free to reopen if you think this is still important enough.
