### ISSUE TITLE
tmt status traceback

### ISSUE THREAD

**Issue by Athwale** [teemtee/tmt#1786]
Running tmt status crashes.
```
python3-tmt-1.20.0-1.fc36.noarch
tmt-1.20.0-1.fc36.noarch
tmt-report-junit-1.20.0-1.fc36.noarch
tmt-report-polarion-1.20.0-1.fc36.noarch
tmt-provision-virtual-1.20.0-1.fc36.noarch
tmt-report-html-1.20.0-1.fc36.noarch
tmt-test-convert-1.20.0-1.fc36.noarch
tmt-provision-container-1.20.0-1.fc36.noarch
tmt-all-1.20.0-1.fc36.noarch
tmt-redhat-utils-1.7-1.fc36.noarch
tmt-redhat-provision-minute-1.7-1.fc36.noarch
tmt-redhat-prepare-errata-1.7-1.fc36.noarch
tmt-redhat-all-1.7-1.fc36.noarch
```

```
$ tmt status
status     id
Traceback (most recent call last):
  File "/usr/bin/tmt", line 20, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/tmt/cli.py", line 1209, in status
    status_obj.show()
  File "/usr/lib/python3.10/site-packages/tmt/base.py", line 2736, in show
    self.process_run(run)
  File "/usr/lib/python3.10/site-packages/tmt/base.py", line 2703, in process_run
    loaded, error = tmt.utils.load_run(run)
  File "/usr/lib/python3.10/site-packages/tmt/utils.py", line 2403, in load_run
    step.load()
  File "/usr/lib/python3.10/site-packages/tmt/steps/execute/__init__.py", line 432, in load
    self._results = [Result.from_serialized(data) for data in results.values()]
  File "/usr/lib/python3.10/site-packages/tmt/steps/execute/__init__.py", line 432, in <listcomp>
    self._results = [Result.from_serialized(data) for data in results.values()]
  File "/usr/lib/python3.10/site-packages/tmt/result.py", line 217, in from_serialized
    name = serialized.pop('name')
KeyError: 'name'
```

**Comment by psss** [comment]
I think the problem is caused by different `tmt` versions which differ in the list of fields, e.g. when a new field is added, the newer `tmt status` is trying to revive a non-existent field.

@Athwale, do you still see the problem? Do you run into it frequently? I'm afraid we currently don't have capacity to properly handle all version combinations. Not sure if initializing such fields to their default values would be a safe option.

**Comment by Athwale** [comment]
I do not run into it frequently, because I abandoned the project where this would have been useful a while ago.

**Comment by psss** [comment]
Ok, let's add it to the backlog with low priority. Marking also as a known issue.

**Comment by psss** [comment]
Similar applies for the `tmt cleanup` command, see also the duplicate issue #1691.
