### ISSUE TITLE
Running `tmt test export --how nitrate` without access to Nitrate results in a traceback

### ISSUE THREAD

**Issue by spetrosi** [teemtee/tmt#1828]
I do not have access to https://tcms.engineering.redhat.com/cases/new/ and when I run the command `tmt test export --how nitrate --ignore-git-validation .` the command fails with the following traceback:
```
Traceback (most recent call last):
  File "/usr/bin/tmt", line 20, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tmt/cli.py", line 637, in tests_export
    test.export(format_=tmt.base.ExportFormat(how))  # type: ignore[call-overload]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tmt/base.py", line 942, in export
    return tmt.export.export_to_nitrate(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tmt/export.py", line 696, in export_to_nitrate
    nitrate_case.update()
  File "/usr/lib/python3.11/site-packages/nitrate/mutable.py", line 1121, in update
    self.tags.update()
  File "/usr/lib/python3.11/site-packages/nitrate/mutable.py", line 67, in update
    self._update()
  File "/usr/lib/python3.11/site-packages/nitrate/containers.py", line 252, in _update
    if added: self._add(added)
              ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/nitrate/containers.py", line 623, in _add
    self._server.TestCase.add_tag(self.id, list(tag.name for tag in tags))
  File "/usr/lib64/python3.11/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/nitrate/xmlrpc_driver.py", line 125, in single_request_with_cookies
    return self.parse_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/xmlrpc/client.py", line 1354, in parse_response
    return u.close()
           ^^^^^^^^^
  File "/usr/lib64/python3.11/xmlrpc/client.py", line 668, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 403: ['Permission denied.']>
```

There should be an error message instead

**Comment by idorax** [comment]
I failed to run the command `tmt test export --how nitrate --ignore-git-validation .`  when reproducing this issue. And I also failed to find the sample config file from the [online documents](https://nitrate.readthedocs.io/en/latest/index.html) of `nitrate`. Hi @spetrosi, would you please share a sample `.nitrate` config file?  Thanks!

```bash
foo$ tmt tests export --how nitrate --ignore-git-validation 
 ERROR  Please, provide at least a minimal config file /home/huanli/.nitrate:
[nitrate]
url = https://nitrate.server/xmlrpc/
No config file found
```

**Comment by lukaszachy** [comment]
@idorax 
```
[nitrate]
url = https://tcms.engineering.redhat.com/xmlrpc/
```
