### ISSUE TITLE
Test import error when there is newline character in Makefile

### ISSUE THREAD

**Issue by jencce** [teemtee/tmt#1844]
We have testcases  Makefiles containing newline character like this:

```
run: $(FILES) build
	( set +o posix; . /usr/bin/rhts_environment.sh; \
. /usr/share/beakerlib/beakerlib.sh; \
. runtest.sh )
```

When importing them, error happens:
```
test: ( set +o posix; . /usr/bin/rhts_environment.sh; \
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/bin/tmt", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/root/upstream/tmt/bin/tmt", line 20, in <module>
    tmt.cli.main()
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/upstream/tmt/tmt/cli.py", line 560, in tests_import
    common, individual = tmt.convert.read(
  File "/root/upstream/tmt/tmt/convert.py", line 514, in read
    read_datafile(path, filename, datafile, types, testinfo)
  File "/root/upstream/tmt/tmt/convert.py", line 264, in read_datafile
    script_paths = [s for s in shlex.split(data['test']) if s.endswith('.sh')]
  File "/usr/lib64/python3.8/shlex.py", line 311, in split
    return list(lex)
  File "/usr/lib64/python3.8/shlex.py", line 300, in __next__
    token = self.get_token()
  File "/usr/lib64/python3.8/shlex.py", line 109, in get_token
    raw = self.read_token()
  File "/usr/lib64/python3.8/shlex.py", line 210, in read_token
    raise ValueError("No escaped character")
ValueError: No escaped character
```

Looks like the newline character is not well handled.

Removing newline characters can work, but we have big bunch of testcases contain this. Is it possible this can be fixed in tmt?

tmt version:
> tmt-1.20.0-1.el8.noarch

**Comment by idorax** [comment]
Currently the [makefile_regex_test](https://github.com/teemtee/tmt/blob/main/tmt/convert.py#L210) is
```python
   210	    makefile_regex_test = r'^run:.*\n\t(.*)$'
```

So it cannot match text like:
```
 'run: $(FILES) build\n'
 '\t( set +o posix; . /usr/bin/rhts_environment.sh; \\\n'
 '. /usr/share/beakerlib/beakerlib.sh; \\\n'
 '. runtest.sh )\n'
```

To fix it, we have to update the related regex.

**Comment by idorax** [comment]
Hi @jencce, for  `run:` in the following,
```
run: $(FILES) build
	( set +o posix; . /usr/bin/rhts_environment.sh; \
. /usr/share/beakerlib/beakerlib.sh; \
. runtest.sh )
```

Can we just fetch the `runtest.sh`? Or the three lines are required? 

CC @lukaszachy， please help to clarify, thanks!

**Comment by lukaszachy** [comment]
Ideally all three lines are converted into working `test` value.

**Comment by idorax** [comment]
Thanks @lukaszachy for clarification! If we return all the three lines, another bug is found, .e.g.
```python
$ python3 -m pdb ~/.virtualenvs/tmt/bin/tmt tests import 
...<snip>...
(Pdb) b tmt/convert.py:535
Breakpoint 1 at /home/huanli/.virtualenvs/tmt/lib/python3.10/site-packages/tmt/convert.py:535
(Pdb) c
Checking the '/home/huanli/dev/1844/foo1' directory.
Makefile found in '/home/huanli/dev/1844/foo1/Makefile'.
task: /kernel/ipmixxx/foo
summary: Test XXX
test: ( set +o posix; . /usr/bin/rhts_environment.sh; \
. /usr/share/beakerlib/beakerlib.sh; \
. runtest.sh )
framework: shell
contact: Rachel Sibley <rasibley@redhat.com>
component: ipmitool
duration: 5m
recommend: beakerlib beakerlib-redhat
> /home/huanli/.virtualenvs/tmt/lib/python3.10/site-packages/tmt/convert.py(535)read()
-> run_target_list.remove(data["test"])
(Pdb) pp data
{'component': ['ipmitool'],
 'contact': 'Rachel Sibley <rasibley@redhat.com>',
 'duration': '5m',
 'extra-summary': '/kernel/ipmixxx/foo',
 'extra-task': '/kernel/ipmixxx/foo',
 'framework': 'shell',
 'recommend': ['beakerlib', 'beakerlib-redhat'],
 'summary': 'Test XXX',
 'test': '( set +o posix; . /usr/bin/rhts_environment.sh; \\\n'
         '. /usr/share/beakerlib/beakerlib.sh; \\\n'
         '. runtest.sh )'}
(Pdb) pp run_target_list
['( set +o posix; . /usr/bin/rhts_environment.sh; \\']
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Pdb) n
ValueError: list.remove(x): x not in list
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> /home/huanli/.virtualenvs/tmt/lib/python3.10/site-packages/tmt/convert.py(535)read()
-> run_target_list.remove(data["test"])
```

Hi @psss, @lukaszachy and @happz, looks we should fix function [def target_content()](https://github.com/teemtee/tmt/blob/main/tmt/convert.py#L517) as well. But I'd like to ask, can we just skip to check the test if it contains `\\\n`?
