### ISSUE TITLE
Can't run tmt from git worktree

### ISSUE THREAD

**Issue by pvalena** [teemtee/tmt#1861]
Or is my git in some invalid /unexpected/ state? I works fine for me....

```
$ tmt plans show -vvv
/all/centos-8
                 summary Test for general vagrant functionality in Fedora
                discover
                     how fmf
                    test
                 exclude
                  filter tag:base
dist-git-remove-fmf-root false
         dist-git-source false
                    link
          dist-git-merge false
           dist-git-init false
           modified-only false
                  fmf-id false
               provision
                     how virtual
              ssh-option
                     key
                    user root
                    arch x86_64
              connection session
                  memory 2048
                   image fedora
                    disk 10
                 prepare
                     how ansible
              extra-args -vvv
                playbook ansible/install_packages.yml
                         ansible/prepare_libvirt.yml
                         ansible/add_user_with_libvirt.yml
                 execute
                     how tmt
                duration 1h
              exit-first false
                  script
             interactive false
                  report
                     how display
                  finish
                     how shell
                  script
             environment DRIVER: kvm
                         BOX: centos/8
                 enabled true
                 sources /home/lpcs/lpcsf-new/test/fedora/vagrant/test/tmt-ci/all.fmf
origin/HEAD set to main
Traceback (most recent call last):
  File "/usr/bin/tmt", line 20, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tmt/cli.py", line 758, in plans_show
    plan.show()
  File "/usr/lib/python3.11/site-packages/tmt/base.py", line 1356, in show
    self._show_additional_keys()
  File "/usr/lib/python3.11/site-packages/tmt/base.py", line 462, in _show_additional_keys
    self._fmf_id()
  File "/usr/lib/python3.11/site-packages/tmt/base.py", line 468, in _fmf_id
    self.fmf_id.to_minimal_dict()), key_color='magenta'))
    ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tmt/base.py", line 478, in fmf_id
    return tmt.utils.fmf_id(self.name, self.node.root)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tmt/utils.py", line 2256, in fmf_id
    def_branch = default_branch(git_root)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tmt/utils.py", line 2396, in default_branch
    with open(head) as ref:
         ^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: '<snip>/vagrant/test/tmt-ci/.git/refs/remotes/origin/HEAD'

$ git status
On branch tmt-ci
Your branch is ahead of 'jackorp/tmt-ci' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

$ ls .git
.git

$ cat .git
gitdir: <snip>/vagrant/test/.git/worktrees/tmt-ci
```

the `test` directory (one above, but the location can be arbitrary) is the one with proper `.git` folder.

**Comment by lukaszachy** [comment]
FTR: https://git-scm.com/docs/git-worktree

You are right, tmt doesn't work in worktree.

Once #1803 is merged the traceback will not appear however default branch will not be obtained properly.

**Comment by pvalena** [comment]
Thanks!

Adding an error message would be great as well!

**Comment by idorax** [comment]
Hi @lukaszachy and @pvalena, PR #1803 is merged, can we close this issue?

**Comment by lukaszachy** [comment]
@idorax Does it work correctly with git worktree? IMO no, see bellow.
```
$ git clone https://github.com/teemtee/tmt REPRO
$ cd REPRO
$ git worktree add TREE quay
$ cd TREE
$ tmt plan show -vvv
.......
                  fmf-id url: https://github.com/teemtee/tmt
                         name: /plans/sanity/lint
```

See that `ref` is missing - we are in TREE directory which corresponds to the 'quay' branch. 
So the expected fmf-id is `ref: quay`

From what I've seen so far the TREE/.git is a file, not directory. IMO it is time to stop parsing .git directly and call git commands instead when possible.
