### ISSUE TITLE
calltrace  when reporting with polarion

### ISSUE THREAD

**Issue by jencce** [teemtee/tmt#2013]
```
Traceback (most recent call last):
  File "/usr/lib64/python3.9/xml/etree/ElementTree.py", line 1047, in _escape_attrib
    if "&" in text:
TypeError: argument of type 'int' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tmt", line 4, in <module>
    __import__('pkg_resources').run_script('tmt==1.22.0', 'tmt')
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 720, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1559, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python3.9/site-packages/tmt-1.22.0-py3.9.egg/EGG-INFO/scripts/tmt", line 62, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.9/site-packages/click-8.1.3-py3.9.egg/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click-8.1.3-py3.9.egg/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click-8.1.3-py3.9.egg/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click-8.1.3-py3.9.egg/click/core.py", line 1689, in invoke
    return _process_result(rv)
  File "/usr/lib/python3.9/site-packages/click-8.1.3-py3.9.egg/click/core.py", line 1626, in _process_result
    value = ctx.invoke(self._result_callback, value, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click-8.1.3-py3.9.egg/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click-8.1.3-py3.9.egg/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tmt-1.22.0-py3.9.egg/tmt/cli.py", line 357, in finito
    click_context.obj.run.go()
  File "/usr/lib/python3.9/site-packages/tmt-1.22.0-py3.9.egg/tmt/base.py", line 2707, in go
    plan.go()
  File "/usr/lib/python3.9/site-packages/tmt-1.22.0-py3.9.egg/tmt/base.py", line 1663, in go
    step.go()
  File "/usr/lib/python3.9/site-packages/tmt-1.22.0-py3.9.egg/tmt/steps/report/__init__.py", line 105, in go
    cast(Union[Action, ReportPlugin], phase).go()
  File "/usr/lib/python3.9/site-packages/tmt-1.22.0-py3.9.egg/tmt/steps/report/polarion.py", line 197, in go
    ET.ElementTree(xml_tree).write(fw)
  File "/usr/lib64/python3.9/xml/etree/ElementTree.py", line 742, in write
    serialize(write, self._root, qnames, namespaces,
  File "/usr/lib64/python3.9/xml/etree/ElementTree.py", line 908, in _serialize_xml
    _serialize_xml(write, e, qnames, None,
  File "/usr/lib64/python3.9/xml/etree/ElementTree.py", line 908, in _serialize_xml
    _serialize_xml(write, e, qnames, None,
  File "/usr/lib64/python3.9/xml/etree/ElementTree.py", line 901, in _serialize_xml
    v = _escape_attrib(v)
  File "/usr/lib64/python3.9/xml/etree/ElementTree.py", line 1070, in _escape_attrib
    _raise_serialization_error(text)
  File "/usr/lib64/python3.9/xml/etree/ElementTree.py", line 1024, in _raise_serialization_error
    raise TypeError(
TypeError: cannot serialize 920 (type int)
```

I installed latest tmt from git repo.

The report part of my plan looks like:
```
report:
    how: polarion
    file: xunit.xml
    project-id: RHELKERNEL
    title: fs-qe connecting to reserved server
    planned-in: 9_2_0
    assignee: xxx
    upload: False
```

The tail of the unfinished xunit.xml:
```
        </testsuite>
<properties><property name="polarion-project-id" value="RHELKERNEL" /><property name="polarion-user-id" value="kernel_machine" /><property name="polarion-testrun-title" value="fs_qe connecting to reserved server" /><property name="polarion-project-span-ids" value="RHELKERNEL" /><property name="polarion-custom-plannedin"
```

Looks like has something to do with the planned-in value. The underscore in 9_2_0 is needed to stay as it is because it matches to the value set in Polarion.

I noticed that in the testrun-title,  dash changes to underscore, which is unnecessary now.

**Comment by psss** [comment]
@jencce, sorry for the late response. Are you still seeing this issue?
