### ISSUE TITLE
Running "tmt clean" on system with tmt_provision_virtual fails with "KeyError: 'discover_phase'"

### ISSUE THREAD

**Issue by bgurney-rh** [teemtee/tmt#2245]
I'm running the following packages on a Fedora 38 system (with KVM, libvirt, and virt_install installed):
tmt-1.25.0-1.fc38.noarch
tmt-provision-virtual-1.25.0-1.fc38.noarch

And so far, I've had some good experiences in using this to perform test runs on new tmt plans, to discover, though trial and error, how to create a working test plan.

Unfortunately, at some point, when I tried running `tmt clean` in the past week or so (recently, after updating from F37 to F38; I'm not sure if that could be a factor), the operation fails with "KeyError: 'discover_phase'".

Here is the full output with traceback:
```
$ tmt clean
clean
guests
Traceback (most recent call last):
  File "/usr/bin/tmt", line 14, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tmt/cli.py", line 1494, in clean
    if not clean_obj.guests():
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tmt/base.py", line 3408, in guests
    if not self._stop_running_guests(run):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tmt/base.py", line 3356, in _stop_running_guests
    loaded, error = tmt.utils.load_run(run)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tmt/utils.py", line 3207, in load_run
    step.load()
  File "/usr/lib/python3.11/site-packages/tmt/steps/discover/__init__.py", line 160, in load
    phase_name = raw_test_datum.pop('discover_phase')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'discover_phase'
```

**Comment by guoguojenna** [comment]
Maybe you can try:

$ tmt clean runs
$ tmt clean guests images runs

**Comment by happz** [comment]
Does this happen always, even with an empty `/var/tmp/tmt`? This looks like an old run facing new tmt which now expects a couple of fields the old tmt never dreamed of saving on disk.

**Comment by bgurney-rh** [comment]
Unfortunately, after I tried a few things, I'm in a state where "tmt clean" now successfully completes:
```
$ tmt clean
clean
guests
runs
images
    testcloud
```

So I don't see the KeyError anymore, though I do see a couple of remnant directories in /var/tmp/tmt: "testcloud" (as seen above), and a run directory ("run-003"), which seems to only contain empty directories.  (I'm okay with removing this entire directory tree.)

Since the original issue, I've executed "dnf update" and restarted the system, so that may be a factor.  But I seem to be free of any errors running "tmt clean".

**Comment by psss** [comment]
Looks like a duplicate of #1786.
