### ISSUE TITLE
tmt status does not show any of the provisioned machines

### ISSUE THREAD

**Issue by mruprich** [teemtee/tmt#2565]
I just upgraded tmt to version 1.30 and tmt status (--abandoned) has empty output even when there is a machine that has been recently provisioned. I usually use tmt like this:
```
1. tmt run -avvv --skip finish execute --how tmt --interactive test --name . provision --how minute --image rhel9 prepare
```
After the test finishes I am able to see the provisioned 1minutetip machine via 1minutetip but not with `tmt status --abandoned`:
```
$ 1minutetip -n -r
I will not start test after boot
[ INFO  ] Select instance which you want to reattach by providing its number
     1	mruprich-1MT-RHEL-9.4.0-20231212.12-6943-1-2023-12-13-11-07 10.0.187.220
Which instance to attach? (number):
$ tmt status --abandoned
status     id

'discover-phase'
```
From the test run, I can see that the id of the machine is for example run-105. I can connect to is via `tmt run`:
```
$ tmt run --id run-105 login
/var/tmp/tmt/run-105

/plans/all
    discover
        status: done
        summary: 1 test selected
    provision
        status: done
        summary: 1 guest provisioned
    prepare
        status: done
        summary: 0 preparations applied
    execute
        status: done
        summary: 1 test executed
    report
        how: display
        login: Starting interactive shell
[root@mruprich-1mt-rhel-9 tree]#
```

**Comment by happz** [comment]
Can you run the `tmt status --abandoned` command with `TMT_SHOW_TRACEBACK=1` envvar set?

**Comment by mruprich** [comment]
@happz Yeah, no problem. So there is a traceback that is probably silenced but I saw this one in 1.29 as well:
```
$ TMT_SHOW_TRACEBACK=1 tmt status --abandoned
status     id

'discover-phase'

    Traceback (most recent call last):
      File "/usr/lib/python3.11/site-packages/tmt/__main__.py", line 18, in run_cli
        tmt.cli.main()
      File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
        return self.main(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
        rv = self.invoke(ctx)
             ^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
        return ctx.invoke(self.callback, **ctx.params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
        return __callback(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
        return f(get_current_context(), *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/tmt/cli.py", line 1697, in status
        status_obj.show()
      File "/usr/lib/python3.11/site-packages/tmt/base.py", line 3669, in show
        self.process_run(run)
      File "/usr/lib/python3.11/site-packages/tmt/base.py", line 3631, in process_run
        loaded, error = tmt.utils.load_run(run)
                        ^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/tmt/utils.py", line 4278, in load_run
        step.load()
      File "/usr/lib/python3.11/site-packages/tmt/steps/discover/__init__.py", line 162, in load
        phase_name = raw_test_datum.pop(key_to_option('discover_phase'))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    KeyError: 'discover-phase'
```

**Comment by happz** [comment]
@mruprich could it be that some rundirs on your laptop would be as old as tmt 1.23, or even older? `discover_phase` key was added in 1.24 to support multihost testing, and I wonder whether this is tmt hitting fairly old workdirs, or whether it's just a regular workdir, created by recent tmt, but with some bug causing it to lack the said key.

**Comment by happz** [comment]
@mruprich could you try `tmt status` with tmt from https://github.com/teemtee/tmt/pull/2573 ? No worries if you cannot, I'll add a test there as well, but it'd be nice to know whether it would fix the problem for you or not.

**Comment by happz** [comment]
> @happz Hi, how do I figure out if some of the rundirs are older?

In this case, they would lack a particular key in `tests.yaml` file. The patch should teach tmt to gracefully report the problem rather than crash and burn, i.e. tmt would detect the issue, report it and move on.

**Comment by psss** [comment]
I believe this is a duplicate of #1786. Feel free to reopen if it's not the case.
