### ISSUE TITLE
tmt cmd will be aborted if one host provision failed 

### ISSUE THREAD

**Issue by guazhang** [teemtee/tmt#2601]
provision multi host,  maybe one of them will provision failed for some reason, but other hosts should continue to run next steps, and now the tmt cmd be aborted.

```
  provision --insert  -h beaker --hardware hostname=xx.redhat.com --image RHEL-9.4.0-20240110.39 
```

```
plan failed

    Traceback (most recent call last):
      File "/usr/lib/python3.11/site-packages/tmt/__main__.py", line 18, in run_cli
        tmt.cli.main()
      File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
        return self.main(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
        rv = self.invoke(ctx)
             ^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/click/core.py", line 1689, in invoke
        return _process_result(rv)
               ^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/click/core.py", line 1626, in _process_result
        value = ctx.invoke(self._result_callback, value, **ctx.params)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
        return __callback(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
        return f(get_current_context(), *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/tmt/cli.py", line 472, in finito
        click_context.obj.run.go()
      File "/usr/lib/python3.11/site-packages/tmt/base.py", line 3511, in go
        raise tmt.utils.GeneralError(
    tmt.utils.GeneralError: plan failed

The exception was caused by 1 earlier exceptions

Cause number 1:

    Failed to create, provisioning failed.

        Traceback (most recent call last):
          File "/usr/lib/python3.11/site-packages/tmt/base.py", line 3507, in go
            plan.go()
          File "/usr/lib/python3.11/site-packages/tmt/base.py", line 2253, in go
            step.go()
          File "/usr/lib/python3.11/site-packages/tmt/steps/provision/__init__.py", line 1930, in go
            phase.go()
          File "/usr/lib/python3.11/site-packages/tmt/steps/provision/mrack.py", line 721, in go
            self._guest.start()
          File "/usr/lib/python3.11/site-packages/tmt/steps/provision/mrack.py", line 651, in start
            self._create(self._tmt_name())
          File "/usr/lib/python3.11/site-packages/tmt/steps/provision/mrack.py", line 625, in _create
            guest_info = tmt.utils.wait(
                         ^^^^^^^^^^^^^^^
          File "/usr/lib/python3.11/site-packages/tmt/utils.py", line 5394, in wait
            ret = check()
                  ^^^^^^^
          File "/usr/lib/python3.11/site-packages/tmt/steps/provision/mrack.py", line 615, in get_new_state
            raise ProvisionError(
        tmt.utils.ProvisionError: Failed to create, provisioning failed.
```

**Comment by happz** [comment]
> but other hosts should continue to run next steps

Should or could? It might be a multihost client/server scenario which would make no longer when the server failed to provision. I guess the best we can do is offer an option, with a sane default, and let the user take control.

**Comment by guazhang** [comment]
> > but other hosts should continue to run next steps
> 
> Should or could? It might be a multihost client/server scenario which would make no longer when the server failed to provision. I guess the best we can do is offer an option, with a sane default, and let the user take control.

 I don't use the client/server scenario, just two or more test server provision in same plan, their tests don't affect each other.
