### ISSUE TITLE
run created unremovable file and workdir cleanup tracebacks

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#283]
I have file I am not able to remove in `/var/tmp/tmt/run-034` which was created by test's `rlFileBackup /etc`  call.

So when I do `tmt run -ddd -vvv -f --id run-034 report`
```python
Clean up workdir '/var/tmp/tmt/run-034'.
Traceback (most recent call last):
  File "/usr/bin/tmt", line 10, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1268, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/tmt/cli.py", line 189, in run
    run = tmt.Run(id_, context.obj.tree, context=context)
  File "/usr/lib/python3.8/site-packages/tmt/base.py", line 745, in __init__
    super().__init__(workdir=id_ or True, context=context)
  File "/usr/lib/python3.8/site-packages/tmt/utils.py", line 113, in __init__
    self._workdir_init(workdir)
  File "/usr/lib/python3.8/site-packages/tmt/utils.py", line 390, in _workdir_init
    self._workdir_cleanup(workdir)
  File "/usr/lib/python3.8/site-packages/tmt/utils.py", line 409, in _workdir_cleanup
    shutil.rmtree(directory)
  File "/usr/lib64/python3.8/shutil.py", line 715, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib64/python3.8/shutil.py", line 652, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib64/python3.8/shutil.py", line 652, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib64/python3.8/shutil.py", line 652, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  [Previous line repeated 4 more times]
  File "/usr/lib64/python3.8/shutil.py", line 656, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib64/python3.8/shutil.py", line 654, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'etc'
```
`
I see this as two (or three) issues
a) Why tmt creates files it cannot remove on _my_ disk
b) Tracebeck itself
c) (maybe) Why is `tmt run -f report` different from `tmt run report -f`

**Comment by lukaszachy** [comment]
Steps to reproduce:
Test is
```sh
$ cat main.fmf 
summary: Concise summary describing what the test does
test: ./test.sh
framework: beakerlib
require: mariadb-server

$ cat test.sh
#!/bin/bash
# vim: dict+=/usr/share/beakerlib/dictionary.vim cpt=.,w,b,u,t,i,k
. /usr/share/beakerlib/beakerlib.sh || exit 1

rlJournalStart
    rlPhaseStartTest
	rlFileBackup --clean /var/lib/mysql
	rlFileRestore
    rlPhaseEnd
rlJournalEnd

```
What I did:
1. `tmt run --id bug -u report provision -h minute`
2. `tmt run -f --id bug -u report provision --how connect -g  A.B.C.D`

**Comment by lukaszachy** [comment]
```sh
$ rm -rf /var/tmp/tmt/bug
rm: cannot remove '/var/tmp/tmt/bug/plans/default/execute/data/repro/backup/var': Permission denied

$ ls -ldZ /var/tmp/tmt/bug/plans/default/execute/data/repro/backup/var
drwxr-xr-x. 2 lzachar lzachar unconfined_u:object_r:user_tmp_t:s0 4096 Dec 15 19:12 /var/tmp/tmt/bug/plans/default/execute/data/repro/backup/var

```

**Comment by lukaszachy** [comment]
Hit this by  /plans/features/advanced and /tests/discover/libraries (run as user, using tests/full: `tmt run -e PLANS=/plans/features/advanced -e TEST_CMD='"tests -n /tests/discover/libraries"'`
