### ISSUE TITLE
Calling to `rstrnt-reboot` with custom command corrupts journal

### ISSUE THREAD

**Issue by pridolfi** [teemtee/tmt#2840]
I'm writing a test that uses `tmt` and `beakerlib`. It calls to `rstrnt-reboot -c "reboot recovery"` to test this specific reboot command.

The system reboots successfully but later on this error is seen in the logs:
```
11:59:14                 out: Traceback (most recent call last):
11:59:14                 out:   File "/usr/bin/beakerlib-journalling", line 361, in <module>
11:59:14                 out:     sys.exit(main())
11:59:14                 out:   File "/usr/bin/beakerlib-journalling", line 357, in main
11:59:14                 out:     return createJournalXML(options)
11:59:14                 out:   File "/usr/bin/beakerlib-journalling", line 318, in createJournalXML
11:59:14                 out:     journal.xpath("starttime")[0].text = starttime
11:59:14                 out: IndexError: list index out of range
11:59:14                 out: :: [ 00:00:13 ] :: [  ERROR   ] :: journal.xml creation failed!
```

Right now the workaround is to call `sync` to flush buffers and create journal files properly just before rebooting. Should this `sync`  be done within `rstrnt-reboot` or `tmt-reboot-core`?

**Comment by psss** [comment]
Yeah, sounds like adding `sync` to the `tmt-reboot-core` would be a good idea. Looks like a simple fix, adding to the backlog with `must` priority.
