### ISSUE TITLE
tmt leapp upgrade failed if the case not in default-0 group

### ISSUE THREAD

**Issue by guazhang** [teemtee/tmt#3067]
the case in `/default-1/` group will failed  while run leapp upgrade tests with tmt, looks the tmt just support case in `default-0 ` group.

from the test log,  tmt will run all case in `default-0 `  group  with `IN_PLACE_UPGRADE=old`,  then run leapp upgrade  and the system will boot to target  OS (here is upgrade from rhel8 to rhel9), then set  `IN_PLACE_UPGRADE=new`, run the `default-0 `  cases again.

after that,  tmt will run `default-1 `  cases with `IN_PLACE_UPGRADE=old`  and run upgrade again,  did it make sense here ?
looks it's new cycle  even though  the system have upgraded.

```
05:25:50         execute task #1: default-0 on default-0
05:25:50         how: upgrade
05:25:50         order: 50
05:25:50         exit-first: false
05:25:50         name: default-0
05:25:50         how: upgrade
05:25:50         order: 50
05:25:50         duration: 1h
05:25:50         url: https://gitlab.cee.redhat.com/oamg/rhel-major-upgrade.git
05:25:50         upgrade_path: /paths/8to9.cut
05:25:50             upgrade: run tests on the old system
05:25:50         Workdir '/var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/default-0' created.
05:25:50         Write file '/var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/data/guest/default-0/old/default-0/tests/reboot-1/metadata.yaml'.
05:25:50         Copy '/usr/lib/python3.11/site-packages/tmt/steps/execute/scripts/tmt-abort' to '/usr/local/bin/tmt-abort' on the guest.
```

```shell
05:46:03         execute task #2: default-1 on default-0
05:46:03         how: upgrade
05:46:03         order: 50
05:46:03         exit-first: false
05:46:03         name: default-0
05:46:03         how: upgrade
05:46:03         order: 50
05:46:03         duration: 1h
05:46:03         url: https://gitlab.cee.redhat.com/oamg/rhel-major-upgrade.git
05:46:03         upgrade_path: /paths/8to9.cut
05:46:03             upgrade: run tests on the old system
05:46:03         Workdir '/var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/default-0' already exists.
05:46:03         Write file '/var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/data/guest/default-0/old/default-1/storage/misc/env_setup-2/metadata.yaml'.
05:46:03         Write file '/var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/data/guest/default-0/old/default-1/storage/block/install_last_package-3/metadata.yaml'.
05:46:03         Write file '/var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/data/guest/default-0/old/default-1/storage/block/log_check-4/metadata.yaml'.
05:46:03         Write file '/var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/data/guest/default-0/old/default-1/storage/block/add_param_to_kernel-5/metadata.yaml'.
05:46:03         Copy '/usr/lib/python3.11/site-packages/tmt/steps/execute/scripts/tmt-abort' to '/usr/local/bin/tmt-abort' on the guest.
```

```
                00:00:01 pass /old/default-1/storage/block/add_param_to_kernel (on default-0) [4/4]
                00:00:00     pass dmesg (before-test check)
                00:00:00     pass avc (after-test check)
                00:00:00     pass dmesg (after-test check)

        Copy '/var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/data' from the guest to '/'.
            upgrade: perform the system upgrade
        how: fmf
        name: upgrade-discover
        order: 50
        Workdir '/var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/upgrade-discover' already exists.
        url: https://gitlab.cee.redhat.com/oamg/rhel-major-upgrade.git
        Clone 'https://gitlab.cee.redhat.com/oamg/rhel-major-upgrade.git' to '/var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/upgrade-discover/tests'.
        Shallow clone of 'https://gitlab.cee.redhat.com/oamg/rhel-major-upgrade.git' failed, let's try with the full history.
        retry: git clone https://gitlab.cee.redhat.com/oamg/rhel-major-upgrade.git /var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/upgrade-discover/tests failed, 3 retries left, trying again in 10.00 seconds.
        fail: Command 'git clone https://gitlab.cee.redhat.com/oamg/rhel-major-upgrade.git /var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/upgrade-discover/tests' returned 128.
        retry: git clone https://gitlab.cee.redhat.com/oamg/rhel-major-upgrade.git /var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/upgrade-discover/tests failed, 2 retries left, trying again in 10.00 seconds.
        fail: Command 'git clone https://gitlab.cee.redhat.com/oamg/rhel-major-upgrade.git /var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/upgrade-discover/tests' returned 128.
        retry: git clone https://gitlab.cee.redhat.com/oamg/rhel-major-upgrade.git /var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/upgrade-discover/tests failed, 1 retries left, trying again in 10.00 seconds.
        fail: Command 'git clone https://gitlab.cee.redhat.com/oamg/rhel-major-upgrade.git /var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/upgrade-discover/tests' returned 128.
        fail: Retries of 'git clone https://gitlab.cee.redhat.com/oamg/rhel-major-upgrade.git /var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/upgrade-discover/tests' unsuccessful.

plan failed

    Traceback (most recent call last):
      File "/usr/lib/python3.11/site-packages/tmt/__main__.py", line 18, in run_cli
        tmt.cli.main()
      File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
        return self.main(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
        rv = self.invoke(ctx)
             ^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/click/core.py", line 1689, in invoke
        return _process_result(rv)
               ^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/click/core.py", line 1626, in _process_result
        value = ctx.invoke(self._result_callback, value, **ctx.params)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
        return __callback(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
        return f(get_current_context(), *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/tmt/cli.py", line 508, in finito
        click_context.obj.run.go()
      File "/usr/lib/python3.11/site-packages/tmt/base.py", line 3576, in go
        raise tmt.utils.GeneralError(
    tmt.utils.GeneralError: plan failed

The exception was caused by 1 earlier exceptions

Cause number 1:

    execute step failed

        Traceback (most recent call last):
          File "/usr/lib/python3.11/site-packages/tmt/base.py", line 3572, in go
            plan.go()
          File "/usr/lib/python3.11/site-packages/tmt/base.py", line 2305, in go
            step.go()
          File "/usr/lib/python3.11/site-packages/tmt/steps/execute/__init__.py", line 936, in go
            raise tmt.utils.GeneralError(
        tmt.utils.GeneralError: execute step failed

    The exception was caused by 1 earlier exceptions

    Cause number 1:

        Retries of 'git clone https://gitlab.cee.redhat.com/oamg/rhel-major-upgrade.git /var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/upgrade-discover/tests' unsuccessful.

            Traceback (most recent call last):
              File "/usr/lib/python3.11/site-packages/tmt/queue.py", line 277, in go
                result = future.result()
                         ^^^^^^^^^^^^^^^
              File "/usr/lib64/python3.11/concurrent/futures/_base.py", line 449, in result
                return self.__get_result()
                       ^^^^^^^^^^^^^^^^^^^
              File "/usr/lib64/python3.11/concurrent/futures/_base.py", line 401, in __get_result
                raise self._exception
              File "/usr/lib64/python3.11/concurrent/futures/thread.py", line 58, in run
                result = self.fn(*self.args, **self.kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/usr/lib/python3.11/site-packages/tmt/steps/__init__.py", line 2172, in run_on_guest
                self.phase.go(guest=guest, logger=logger)
              File "/usr/lib/python3.11/site-packages/tmt/steps/execute/upgrade.py", line 199, in go
                self._perform_upgrade(guest, logger)
              File "/usr/lib/python3.11/site-packages/tmt/steps/execute/upgrade.py", line 317, in _perform_upgrade
                self._fetch_upgrade_tasks()
              File "/usr/lib/python3.11/site-packages/tmt/steps/execute/upgrade.py", line 237, in _fetch_upgrade_tasks
                self._run_discover_upgrade()
              File "/usr/lib/python3.11/site-packages/tmt/steps/execute/upgrade.py", line 254, in _run_discover_upgrade
                self._discover_upgrade.go()
              File "/usr/lib/python3.11/site-packages/tmt/steps/discover/fmf.py", line 361, in go
                tmt.utils.git_clone(
              File "/usr/lib/python3.11/site-packages/tmt/utils.py", line 5317, in git_clone
                return retry(
                       ^^^^^^
              File "/usr/lib/python3.11/site-packages/tmt/utils.py", line 7096, in retry
                raise RetryError(label, causes=exceptions)
            tmt.utils.RetryError: Retries of 'git clone https://gitlab.cee.redhat.com/oamg/rhel-major-upgrade.git /var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/upgrade-discover/tests' unsuccessful.

        The exception was caused by 3 earlier exceptions

        Cause number 1:

            Command 'git clone https://gitlab.cee.redhat.com/oamg/rhel-major-upgrade.git /var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/upgrade-discover/tests' returned 128.

            stderr (1/1 lines)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            fatal: destination path '/var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/upgrade-discover/tests' already exists and is not an empty directory.
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


                Traceback (most recent call last):
                  File "/usr/lib/python3.11/site-packages/tmt/utils.py", line 7087, in retry
                    return func(*args, **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^
                  File "/usr/lib/python3.11/site-packages/tmt/utils.py", line 5293, in clone_the_repo
                    return Command('git', 'clone', *depth, url, destination).run(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                  File "/usr/lib/python3.11/site-packages/tmt/utils.py", line 1381, in run
                    raise RunError(
                tmt.utils.RunError: Command 'git clone https://gitlab.cee.redhat.com/oamg/rhel-major-upgrade.git /var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/upgrade-discover/tests' returned 128.

        Cause number 2:

            Command 'git clone https://gitlab.cee.redhat.com/oamg/rhel-major-upgrade.git /var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/upgrade-discover/tests' returned 128.

            stderr (1/1 lines)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            fatal: destination path '/var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/upgrade-discover/tests' already exists and is not an empty directory.
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


                Traceback (most recent call last):
                  File "/usr/lib/python3.11/site-packages/tmt/utils.py", line 7087, in retry
                    return func(*args, **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^
                  File "/usr/lib/python3.11/site-packages/tmt/utils.py", line 5293, in clone_the_repo
                    return Command('git', 'clone', *depth, url, destination).run(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                  File "/usr/lib/python3.11/site-packages/tmt/utils.py", line 1381, in run
                    raise RunError(
                tmt.utils.RunError: Command 'git clone https://gitlab.cee.redhat.com/oamg/rhel-major-upgrade.git /var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/upgrade-discover/tests' returned 128.

        Cause number 3:

            Command 'git clone https://gitlab.cee.redhat.com/oamg/rhel-major-upgrade.git /var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/upgrade-discover/tests' returned 128.

            stderr (1/1 lines)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            fatal: destination path '/var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/upgrade-discover/tests' already exists and is not an empty directory.
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


                Traceback (most recent call last):
                  File "/usr/lib/python3.11/site-packages/tmt/utils.py", line 7087, in retry
                    return func(*args, **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^
                  File "/usr/lib/python3.11/site-packages/tmt/utils.py", line 5293, in clone_the_repo
                    return Command('git', 'clone', *depth, url, destination).run(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                  File "/usr/lib/python3.11/site-packages/tmt/utils.py", line 1381, in run
                    raise RunError(
                tmt.utils.RunError: Command 'git clone https://gitlab.cee.redhat.com/oamg/rhel-major-upgrade.git /var/tmp/tmt/2024_07_01_13_12_02_3zmsvp75VnJC/plan/reserve/execute/upgrade-discover/tests' returned 128.

```

```shell
05:12:12         summary: 5 tests selected
05:12:12             /default-0/tests/reboot
05:12:12             /default-1/storage/misc/env_setup
05:12:12             /default-1/storage/block/install_last_package
05:12:12             /default-1/storage/block/log_check
05:12:12             /default-1/storage/block/add_param_to_kernel
05:12:12     status: done
```

```shell

discover:
  - how: fmf
    test:
      - /tests/reboot
    order: 40
  - how: fmf
    url: https://gitlab.cee.redhat.com/kernel-qe/kernel.git
    test:
      - /storage/misc/env_setup
      - /storage/block/install_last_package
      - /storage/block/log_check
      - /storage/block/add_param_to_kernel
    order: 49



adjust:
  - when: UPGRADE == 8to9
    environment+:
        LEAPP_OVL_IMG_FS_EXT4: 1
        LEAPP_DEVEL_SKIP_CHECK_OS_RELEASE: 1
    execute:
    - how: upgrade
      url: https://gitlab.cee.redhat.com/oamg/rhel-major-upgrade.git
      upgrade-path: /paths/8to9.cut


```

**Comment by psss** [comment]
@guazhang, do you still see the problem with the latest `tmt`?

**Comment by therazix** [comment]
@guazhang ping

**Comment by guazhang** [comment]
Hi, 

it's should same with https://github.com/teemtee/tmt/issues/3894 I think.
