### ISSUE TITLE
CheckPlugin doesn't like inherited checks

### ISSUE THREAD

**Issue by martinhoyer** [teemtee/tmt#3335]
Fortunately not a regression, reproduced with previous tmt versions.
It seems that it can only be reproduced when `check:` is inherited, not when added specifically to a test. :confused: 
Noticed when testing tmt-web.

```
>>> from tmt.base import Tree
>>> from tmt import Logger
>>> tree = Tree(logger=Logger.get_bootstrap_logger())
>>> tests = tree.tests(names=['tests/execute/result'])
Traceback (most recent call last):
  File "/home/mhoyer/repos/tmt/tmt/checks/__init__.py", line 260, in normalize_test_check
    return CheckPlugin.delegate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mhoyer/repos/tmt/tmt/checks/__init__.py", line 211, in delegate
    return cast(CheckPlugin[CheckT], find_plugin(raw_data['how'])) \
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mhoyer/repos/tmt/tmt/checks/__init__.py", line 60, in find_plugin
    raise tmt.utils.GeneralError(
tmt.utils.GeneralError: Test check 'dmesg' was not found in check registry.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mhoyer/repos/tmt/tmt/base.py", line 3075, in tests
    Test(
  File "/home/mhoyer/repos/tmt/tmt/base.py", line 1201, in __init__
    super().__init__(
  File "/home/mhoyer/repos/tmt/tmt/base.py", line 718, in __init__
    super().__init__(node=node, logger=logger, parent=parent, name=node.name, **kwargs)
  File "/home/mhoyer/repos/tmt/tmt/utils/__init__.py", line 5105, in __init__
    super().__init__(node=node, logger=logger, **kwargs)
  File "/home/mhoyer/repos/tmt/tmt/utils/__init__.py", line 5736, in __init__
    self._load_keys(node.get(), node.name, logger)
  File "/home/mhoyer/repos/tmt/tmt/utils/__init__.py", line 5709, in _load_keys
    value = dataclass_normalize_field(self, key_address, keyname, value, logger)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mhoyer/repos/tmt/tmt/utils/__init__.py", line 5131, in dataclass_normalize_field
    value = metadata.normalize_callback(key_address, raw_value, logger)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mhoyer/repos/tmt/tmt/checks/__init__.py", line 304, in normalize_test_checks
    normalize_test_check(f'{key_address}[{i}]', raw_test_check, logger)
  File "/home/mhoyer/repos/tmt/tmt/checks/__init__.py", line 265, in normalize_test_check
    raise tmt.utils.SpecificationError(
tmt.utils.SpecificationError: Cannot instantiate check from '/tests/execute/result/basic:check[0]'.
```

**Comment by martinhoyer** [comment]
I see, `tmt.plugins.explore()` needs to be run first. Let me try that in the tmt-web.

**Comment by martinhoyer** [comment]
yep, tmt-web issue, sorry for the noise.
