### ISSUE TITLE
cyclical beakerlib libraries dependency is not handled

### ISSUE THREAD

**Issue by sopos** [teemtee/tmt#492]
Requiring following libraries causes the issue:
`https://github.com/beakerlib/distribution/tree/master/Log`, `https://github.com/beakerlib/distribution/tree/master/opts`

Currently the _opts_ library has the requirement commented out to avoid the issue.

```
    discover
        workdir: /var/tmp/tmt/run-012/plans/default/discover
        how: fmf
        order: 50
            Run command 'git rev-parse --show-toplevel'.
            out: /home/dapospis/test/git/SP_components/tests
        directory: /home/dapospis/test/git/SP_components/tests
            Copy '/home/dapospis/test/git/SP_components/tests' to '/var/tmp/tmt/run-012/plans/default/discover/default/tests'.
            Check metadata tree in '/var/tmp/tmt/run-012/plans/default/discover/default/tests/'.
            Detected library 'library(distribution/dpcommon)'.
            Fetch library 'distribution/dpcommon'.
            Run command 'git clone https://github.com/beakerlib/distribution /var/tmp/tmt/run-012/plans/default/discover/default/libs/distribution'.
            err: Cloning into '/var/tmp/tmt/run-012/plans/default/discover/default/libs/distribution'...
            Run command 'git checkout master'.
            err: Already on 'master'
            out: Your branch is up to date with 'origin/master'.
            Detected library 'library(distribution/tcf)'.
            Library 'distribution/tcf' already fetched.
            Detected library 'library(distribution/Log)'.
            Library 'distribution/Log' already fetched.
            Detected library 'library(distribution/opts)'.
            Library 'distribution/opts' already fetched.
            Detected library 'library(distribution/Log)'.
            Library 'distribution/Log' already fetched.
            Detected library 'library(distribution/opts)'.
            Library 'distribution/opts' already fetched.
            Detected library 'library(distribution/Log)'.
            Library 'distribution/Log' already fetched.
            Detected library 'library(distribution/opts)'.
            Library 'distribution/opts' already fetched.
            Detected library 'library(distribution/Log)'.
            Library 'distribution/Log' already fetched.
            Detected library 'library(distribution/opts)'.
...
Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1290, in invoke
    return _process_result(rv)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1224, in _process_result
    value = ctx.invoke(self.result_callback, value, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tmt/cli.py", line 280, in finito
    click_context.obj.run.go()
  File "/usr/lib/python3.9/site-packages/tmt/base.py", line 990, in go
    plan.go()
  File "/usr/lib/python3.9/site-packages/tmt/base.py", line 572, in go
    step.go()
  File "/usr/lib/python3.9/site-packages/tmt/steps/discover/__init__.py", line 125, in go
    plugin.go()
  File "/usr/lib/python3.9/site-packages/tmt/steps/discover/fmf.py", line 165, in go
    test.require, test.recommend, _ = tmt.beakerlib.dependencies(
  File "/usr/lib/python3.9/site-packages/tmt/beakerlib.py", line 212, in dependencies
    requires, recommends, libraries = dependencies(
  File "/usr/lib/python3.9/site-packages/tmt/beakerlib.py", line 212, in dependencies
    requires, recommends, libraries = dependencies(
  File "/usr/lib/python3.9/site-packages/tmt/beakerlib.py", line 212, in dependencies
    requires, recommends, libraries = dependencies(
  [Previous line repeated 969 more times]
  File "/usr/lib/python3.9/site-packages/tmt/beakerlib.py", line 209, in dependencies
    library = Library(dependency, parent=parent)
  File "/usr/lib/python3.9/site-packages/tmt/beakerlib.py", line 92, in __init__
    self.fetch()
  File "/usr/lib/python3.9/site-packages/tmt/beakerlib.py", line 118, in fetch
    self.parent.debug(f"Library '{self}' already fetched.", level=3)
  File "/usr/lib/python3.9/site-packages/tmt/utils.py", line 237, in debug
    self._log(self._indent(key, value, color=None, shift=shift))
  File "/usr/lib/python3.9/site-packages/tmt/utils.py", line 209, in _log
    self.parent._log(message)
  File "/usr/lib/python3.9/site-packages/tmt/utils.py", line 209, in _log
    self.parent._log(message)
  File "/usr/lib/python3.9/site-packages/tmt/utils.py", line 209, in _log
    self.parent._log(message)
  File "/usr/lib/python3.9/site-packages/tmt/utils.py", line 212, in _log
    log.write(remove_color(message) + '\n')
  File "/usr/lib/python3.9/site-packages/tmt/utils.py", line 935, in remove_color
    return re.sub(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])', '', text)
  File "/usr/lib64/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib64/python3.9/re.py", line 291, in _compile
    if isinstance(flags, RegexFlag):
ecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by sopos** [comment]
As a workaround I removed the requirement for the _Log_ library from the _opts_ library as normally tests / libs require _Log_ library not the _opts_ or both at the same time.

To reproduce the issue one needs to have two libraries which require each other.

**Comment by RHEmployee** [comment]
Hi. I finally have working reproducer so I can try to handle this. Seems to be free.
Feel free to let me know if you want to work on this.

**Comment by RHEmployee** [comment]
There is first draft, but it seems like interesting rabbit hole so I need to figure out how to debug tmt code running on virtual machine...
https://github.com/teemtee/tmt/pull/1149

Virtual machine output:
    prepare
        how: install
        summary: Install required packages
        name: requires
        package: beakerlib and library(testprd/Logs)
... then nothing

**Comment by psss** [comment]
What about just running with the full debug mode using `tmt run -vvvddd`? For example:

```
> cd tests/discover/libraries/data/
> tmt run -vvvddd discover plan --name apache
...
    discover
        workdir: /var/tmp/tmt/run-304/plan/apache/discover
        how: fmf
        order: 50
            Run command 'git rev-parse --show-toplevel'.
            out: /home/psss/git/tmt
        directory: /home/psss/git/tmt
            Copy '/home/psss/git/tmt' to '/var/tmp/tmt/run-304/plan/apache/discover/default/tests'.
            Run command 'git rev-parse --short HEAD'.
            out: 4dc7a31
        hash: 4dc7a31
        path: tests/discover/libraries/data
        tests: apache
            Check metadata tree in '/var/tmp/tmt/run-304/plan/apache/discover/default/tests/tests/discover/libraries/data'.
            Detected library 'library(httpd/http)'.
            Fetch library 'httpd/http'.
            Run command 'git clone https://github.com/beakerlib/httpd /var/tmp/tmt/run-304/plan/apache/discover/default/libs/httpd'.
            err: Cloning into '/var/tmp/tmt/run-304/plan/apache/discover/default/libs/httpd'...
            Run command 'git checkout master'.
            err: Already on 'master'
            out: Your branch is up to date with 'origin/master'.
            Detected library 'library(openssl/certgen)'.
            Fetch library 'openssl/certgen'.
            Run command 'git clone https://github.com/beakerlib/openssl /var/tmp/tmt/run-304/plan/apache/discover/default/libs/openssl'.
            err: Cloning into '/var/tmp/tmt/run-304/plan/apache/discover/default/libs/openssl'...
            Run command 'git checkout master'.
            err: Already on 'master'
            out: Your branch is up to date with 'origin/master'.
            Detected library '{'url': 'https://github.com/redhat-qe-security/certgen', 'name': '/certgen'}'.
            Fetch library 'certgen/certgen'.
            Run command 'git clone https://github.com/redhat-qe-security/certgen /var/tmp/tmt/run-304/plan/apache/discover/default/libs/certgen'.
            err: Cloning into '/var/tmp/tmt/run-304/plan/apache/discover/default/libs/certgen'...
            Run command 'git checkout master'.
            err: Already on 'master'
            out: Your branch is up to date with 'origin/master'.

```

Btw, the library fetching happens during the `discover` step, not `prepare`. Only libraries which cannot be fetched from git are handed over to `prepare` to try to install it using the old rpm way.

**Comment by RHEmployee** [comment]
Ok. Looks like it works now. Maybe it was slow because my machine.
I think, there is another way how to fix this issue, but for now I'm happy that I was able to crack this.
