### ISSUE TITLE
Traceback for 'run --last login'

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#973]
I very likely didn't run it correctly but tmt shouldn't traceback (edit: missing 'provision' in 2nd step)

tmt version: 1.9.0 (599b9a1)

To reproduce
1. tmt run provision -h v -i <IMAGE>
2. tmt run --last login finish

```
/plans/default
Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1700, in invoke
    return _process_result(rv)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1637, in _process_result
    value = ctx.invoke(self._result_callback, value, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/tmt/cli.py", line 337, in finito
    click_context.obj.run.go()
  File "/usr/lib/python3.10/site-packages/tmt/base.py", line 1586, in go
    plan.go()
  File "/usr/lib/python3.10/site-packages/tmt/base.py", line 884, in go
    step.setup_actions()
  File "/usr/lib/python3.10/site-packages/tmt/steps/__init__.py", line 164, in setup_actions
    for plugin in Login.plugins(step=self):
  File "/usr/lib/python3.10/site-packages/tmt/steps/__init__.py", line 583, in plugins
    return [Login(step, phase) for phase in cls.phases(step)]
  File "/usr/lib/python3.10/site-packages/tmt/steps/__init__.py", line 423, in phases
    cls._phases = cls._parse_phases(step)
  File "/usr/lib/python3.10/site-packages/tmt/steps/__init__.py", line 447, in _parse_phases
    phases[login_during.name] = [PHASE_END]
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by idorax** [comment]
@lukaszachy, I had a try to reproduce this issue, but hit a problem - `Could not map '001' to compose.`,  is there anything wrong by running command `tmt run provision -h v -i 001`?
```
(tmt) huanli@tmta:foo$ cat -n plans/foo.fmf 
     1	summary: Basic smoke test
     2	discover:
     3	    how: fmf
     4	provision:
     5	    how: local
     6	execute:
     7	    how: tmt
(tmt) huanli@tmta:foo$ tmt run provision -h v -i 001
/var/tmp/tmt/run-001

/plans/foo
    provision
        how: v
        image: 001
        user: root
        memory: 2048 MB
        disk: 10 GB
        arch: x86_64
Could not map '001' to compose.
```

**Comment by lukaszachy** [comment]
Well, it was filled for 1.9.0, now we have 1.14.0

Your `tmt run provision -h v -i 001` is processed by tmt correctly - you asked for image called "001" and tmt cannot translate it to anything it knows (yeah, error could be better)

IMO we can close this as not relevant any more.

**Comment by lukaszachy** [comment]
So I used tmt from 1.9.0 and reproduced the issue with
```
$ tmt run provision -h v
$ tmt run --last login finish
/var/tmp/tmt/run-100

/plans/default
Traceback (most recent call last):
  File "/home/lzachar/.virtualenvs/tmt/bin/tmt", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/lzachar/gits/tmt/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 1689, in invoke
    return _process_result(rv)
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 1626, in _process_result
    value = ctx.invoke(self._result_callback, value, **ctx.params)
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/lzachar/gits/tmt/tmt/cli.py", line 337, in finito
    click_context.obj.run.go()
  File "/home/lzachar/gits/tmt/tmt/base.py", line 1586, in go
    plan.go()
  File "/home/lzachar/gits/tmt/tmt/base.py", line 884, in go
    step.setup_actions()
  File "/home/lzachar/gits/tmt/tmt/steps/__init__.py", line 164, in setup_actions
    for plugin in Login.plugins(step=self):
  File "/home/lzachar/gits/tmt/tmt/steps/__init__.py", line 583, in plugins
    return [Login(step, phase) for phase in cls.phases(step)]
  File "/home/lzachar/gits/tmt/tmt/steps/__init__.py", line 423, in phases
    cls._phases = cls._parse_phases(step)
  File "/home/lzachar/gits/tmt/tmt/steps/__init__.py", line 447, in _parse_phases
    phases[login_during.name] = [PHASE_END]
AttributeError: 'NoneType' object has no attribute 'name'

```

Same commands work without any issue on current main (and 1.14.0) --> Thus this got fixed by some other commit in the mean time
